name: zone
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.6.6+419

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  rwkv_mobile_flutter:
    path: ../

  photo_viewer:
    git:
      url: https://github.com/HaloWang/photo_viewer
      ref: main

  adaptive_dialog: ^2.4.0
  audioplayers:
  background_downloader:
  collection:
  crypto:
  cupertino_icons:
  equatable:
  file_picker:
  flutter_dotenv:
  flutter_markdown:
  flutter_native_splash:
  flutter_riverpod:
  freezed_annotation:
  gaimon:
  go_router:
  halo: ^0.7.2
  halo_alert:
  halo_state:
  http:
  image_picker:
  intl:
  json_annotation:
  package_info_plus:
  path:
  path_provider:
  permission_handler:
  record:
  sentry_flutter:
  share_plus:
  shared_preferences:
  system_info2:
  url_launcher:
  vclibs:

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_gen_runner:
  flutter_lints:
  freezed:
  icons_launcher:
  json_serializable:
  riverpod_lint:
  sentry_dart_plugin: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/lib/chat/
    - assets/model/chat/
    - assets/config/chat/
    - assets/img/chat/
    - assets/lib/qnn/
    - demo-config.json
    - .env
    - assets/filter.txt

flutter_intl:
  enabled: true # Required. Must be set to true to activate the package. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en
  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/gen # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: rwkv0
  org: ce-wang
